pipeline {
    agent any
    tools {
        maven 'maven16'
    }
    stages {
        stage("test_app") {
            steps {
                script { 
                    echo "Testing The Application"
                    sh '''
                    cd Full-CI-CD-Project
                    mvn test 
                    '''        
                }
            }
        }

        stage("build_jar") {
            steps {
                script { 
                    echo "Building The Application"
                    sh '''
                    cd Full-CI-CD-Project
                    mvn clean package 
                    '''        
                }
            }
        }

        stage("build_docker_image") {
            steps {
                script { 
                    echo "Building Docker Image "
                    withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', passwordVariable: 'PASSWORD', usernameVariable: 'USERNAME')]) {
                        sh '''
                        docker build -t omaralaa87/myapp:1.2 Full-CI-CD-Project/
                        echo $PASSWORD | docker login -u $USERNAME --password-stdin
                        '''
                    }
                }
            }
        }

        stage("push_to_dockerhub") {
            steps {
                script { 
                    echo "Pushing Application To Dockerhub"
                    sh 'docker push omaralaa87/myapp:1.2'
                }
            }
        }

        stage("DeployApp") {
            steps {
                script { 
                    echo "Deploying The Application"
                    sshagent(['ec2-ssh']) {
                        sh '''
                        ssh -o StrictHostKeyChecking=no ubuntu@18.207.155.128 << EOF
                        sudo docker stop myapp || true
                        sudo docker rm myapp || true
                        sudo docker pull omaralaa87/myapp:1.2
                        sudo docker run -d -p 8080:8080 --name myapp omaralaa87/myapp:1.2
                        EOF
                        '''
                    }
                }
            }
        }
    }
}

