pipeline{
    agent any
    tools {
        maven 'maven16'
    }
    stages {
        stage("test_app"){
            steps{
                script{ 
                    echo "Testing The Application"
                    sh '''
                    cd Full-CI-CD-Project
                    mvn test 
                    '''        
                }
            }
        }

        stage("build_jar"){
            steps{
                script{ 
                    echo "Building The Application"
                    sh '''
                    cd Full-CI-CD-Project
                    mvn clean package 
                    '''        
                }
            }
        }
        stage("build_docker_image"){
            steps{
                script{ 
                    echo "Building Docker Image "
                    withCredentials([usernamePassword(credentialsId:'docker-hub-credentials', passwordVariable:'PASSWORD', usernameVariable:'USERNAME' )])
                    {
                    sh 'docker build -t omaralaa87/myapp:1.2 Full-CI-CD-Project/'
                    sh "echo $PASSWORD | docker login -u $USERNAME --password-stdin"
                    }
                }
            }
        }
        stage("push to dockerhub"){
            steps{
                script{ echo "Deploying Application To Dockerhub"
                        sh 'docker push omaralaa87/myapp:1.2'

                }
            }
        }

    }




}
